config/routes.rb
Rails.application.routes.draw do

  root "homes#show"

  get "auth/foursquare", as: :foursquare_login
  get "auth/foursquare/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/venues/search", to: 'venues#search'

  resources :venues, only: [:index, :show]

  resources :users, only: [:show]

end

app/models/category.rb
class Category < OpenStruct


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :user_name, :user_id

  def service
    @@service ||= UserService.new
  end

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid         = auth_info.uid
      new_user.name        = auth_info.info.name
      new_user.oauth_token = auth_info.credentials.token
    end
  end

  def photo(user)
    user_photo_hash = self.service.get_user_info(user.uid)
    user_photo_prefix = user_photo_hash["response"]["user"]["photo"]["prefix"]
    user_photo_suffix = user_photo_hash["response"]["user"]["photo"]["suffix"]
    user_photo_prefix + user_photo_suffix.split("/")[1]
  end

  def user_name(user)
    user_name_hash = self.service.get_user_info(user.uid)
    user_name_first = user_name_hash["response"]["user"]["firstName"]
    user_name_last = user_name_hash["response"]["user"]["lastName"]
    user_name_first + user_name_last
  end

  def check_in_count(user)
    check_ins_hash = self.service.get_check_ins(user.uid)
    check_ins_count = check_ins_hash["response"]["checkins"].first[1]
  end

  def last_check_ins(user)
    last_checkin_hash = self.service.get_check_ins(user.uid)
    top_5_check_ins = last_checkin_hash["response"]["checkins"]["items"][0..4]
    venues_of_check_ins = top_5_check_ins.map { |check_in| Venue.new(check_in["venue"]) }
    time_of_check_ins = top_5_check_ins.map { |check_in| format_date(check_in["createdAt"]) }
    venues_of_check_ins.zip(time_of_check_ins)
  end

  def format_date(epoch_time)
    date_time = DateTime.strptime("#{epoch_time}", "%s")
    date_time.strftime("%m%d%Y")
  end
end

app/models/venue.rb
class Venue < OpenStruct

  def self.service
    @@service ||= VenueService.new
  end

  def self.all
    venues_hash = service.get_venues
    venues_data = venues_hash["response"]["venues"]["items"]
    venues_data.map do |venue_data|
      Venue.new(venue_data)
    end
  end

  # def create_venues_objects(parsed_data_sets)
  #   map do |parsed_data_set|
  #     Venue.new(parsed_data_set)
  #   end
  # end

  def self.find(params_id)
    venue = self.service.get_venue_basic_info(params_id)
    Venue.new(venue["response"]["venue"])
  end

  def self.categories
    category_hash = service.get_categories
    categories = category_hash["response"]["categories"]
    categories.map do |category|
      Category.new(category)
    end
  end

  def self.search_location(city, state)
   if city && state
     location = city + ", " + state
     search_venue_hash  = service.get_venues_by_location(location)
     top_search_venues = search_venue_hash["response"]["venues"][0..20]
     top_search_venues.map do |venue|
       Venue.new(venue)
      end
    else
      nil
    end
  end

  def self.search_location_category(city, state, category_id)
    if city && state && category_id
      location = city + ", " + state
      category_location_search_hash = service.get_venue_by_location_category(category_id, location)
      category_location_search = category_location_search_hash["response"]["venues"][0..20]
      category_location_search.map do |venue|
        Venue.new(venue)
      end
    else
      nil
    end
  end

  def tips
    tips_hash = service.get_tips(self.id)
    tips = tips_hash["response"]["tips"]["items"][0..4]
    tips.map {|tip| tip["text"]}
  end

private
  def service
    @@service ||= VenueService.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user_check_ins_total = current_user.check_in_count(current_user)
    @user_name = current_user.user_name(current_user)
    @user_photo = current_user.photo(current_user)
    @last_5_check_ins = current_user.last_check_ins(current_user)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def index
    @venues = Venue.all
  end

  def show
    @venue = Venue.find(params[:id])
    @venue_stats = @venue.check_in_stats
    @venue_tips = @venue.tips
  end

  def search
    @category = Venue.categories
    if params[:category]
      @venues_category_city = Venue.search_location_category(params[:city], params[:state], params[:category])
    else
      @venues = Venue.search_location(params[:city], params[:state])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_state_helper.rb
module CityStateHelper

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def us_cities
    [["Los Angeles"],
     ["Seattle"],
     ["Denver"],
     ["New York City"],
     ["Miami"],
     ["Chicago"],
     ["Houston"],
     ["San Francisco"]
    ]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/show.html.erb
<div class="container">

  <h1>Welcome</h1>
  <% if current_user %>
    <%= link_to "See User Stats", user_path(current_user.id)  %></br></br>
    <%= link_to "See User's Check-in Venues", venues_path %>
  <% else  %>
    <p> Please Login </p>
  <% end  %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
     <a class="brand brand-name-landing-page navbar-left" href="/">What's Around</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="custom-nav"> <%= link_to "Hello, #{current_user.name}", user_path(current_user.id) %></li>
          <li class="custom-nav"><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li class="custom-nav"><%= link_to "Login with Foursquare", foursquare_login_path %></li>
        <% end  %>
        </li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatsAround</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<div class="container">

  <h1>Welcome, <%= @user_name %></h1>
  <p><%= image_tag(@user_photo) %></p>
  <p>My Check-In Count: <%= @user_check_ins_total %></p>
  <ul>
  <% @last_5_check_ins.each do |check_in|  %>
    <li><%= link_to check_in[0].name, venue_path(check_in[0].id) %></li>
      <ul>
        <li>Date of Checkin: <%= check_in[1] %></li>
      </ul>
  <% end %>
  </ul>
</div>

app/views/venues/index.html.erb
<div class="container">

  <h1>All My Check-Ins</h1>
  <div class="text-center">
  <%= link_to "Search More Venues", venues_search_path, class:"btn btn-default " %>
  </div>
  <ul>
    <% @venues.each do |venue| %>
    <li><%= link_to venue["venue"]["name"], venue_path(venue["venue"]["id"]) %></li>
    <% end %>
   </ul>

</div>

app/views/venues/search.html.erb
<div class="container">

  <h3> Select For a Venue<h3>

  <%= form_tag venues_search_path, :method => 'get' do %>
    <%= select_tag :city, options_for_select(us_cities)   %>
    <%= select_tag :state, options_for_select(us_states) %>
    <%= select_tag :category, options_for_select(@category.map { |category| [category.name, category.id]}), :include_blank=>true%>
    <%= submit_tag "Search", :name => nil %>
  <% end %>

  <% if @venues %>
  <h2>Results:</h2>
    <ul>
    <% @venues.each do |venue| %>
        <li> <%= link_to venue.name, venue_path(venue.id)  %></li>
    <%end  %>
    </ul>
  <% end %>

  <% if @venues_category_city %>
  <h2>Results:</h2>
    <ul>
    <% @venues_category_city.each do |venue| %>
        <li> <%= link_to venue.name, venue_path(venue.id)  %></li>
    <%end  %>
    </ul>
  <% end %>

</div>

app/views/venues/show.html.erb
<div class="container">

  <h1><%= @venue.name %></h1>
  General Info:
  <ul>
    <%if @venue.location["address"] %>
      <li>Address: <%= @venue.location["address"] %></li>
      <li>City: <%= @venue.location["city"] %></li>
    <% end %>
      <li>State: <%= @venue.location["state"] %></li>
      <li>Post Code: <%= @venue.location["postalCode"] %></li>
      <li>Category:  <%= @venue.categories.first["name"] %></li>
    <% if @venue.hours %>
      <li>Days Open: <%= @venue.hours["timeframes"].first["days"] %></li>
      <li>Hours: <%= @venue.hours["timeframes"].first["open"].first["renderedTime"] %></li>
    <% end  %>
    </ul>

  Tips:
  <ul>
  <% @venue_tips.each do |tip| %>
    <li><%= tip %></li>
   <% end  %>
  </ul>

</div>